CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  storyblok_user_id TEXT,
  contentful_user_id TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
